<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>sm-tagger</AssemblyName>
    <RootNamespace>SmTagger</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SmTagger.Engine/SmTagger.Engine.csproj" />
  </ItemGroup>
</Project>
