<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>sm-sorter</AssemblyName>
    <RootNamespace>SmSorter</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SmTagger.Tests" />
    <ProjectReference Include="../SmTagger.Shared/SmTagger.Shared.csproj" />
  </ItemGroup>
</Project>
